name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Copy files
      run : cp -a ./rust ./home/runner/work/extract_jsons_from_string/extract_jsons_from_string
    - name: Change working directory
      run: cd rust
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
