name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Tree
      run: tree
    - name: Change working directory
      run: cd rust
    - name: Build
      run: cargo build  --manifest-path=rust/Cargo.toml--verbose 
    - name: Run tests
      run: cargo test --verbose
